name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - 'papers/**'
      - 'rfcs/**'
      - '*.md'

jobs:
  build:
    strategy:
      matrix:
        os: [{name: ubuntu, version: ubuntu-20.04}, {name: macos, version: macos-latest}, {name: windows, version: windows-latest}]
    name: ${{matrix.os.name}}
    runs-on: ${{matrix.os.version}}
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: cmake --build . --target Luau.Repl.CLI Luau.Analyze.CLI --config Release -j 2
    - uses: actions/upload-artifact@v2
      if: matrix.os.name != 'windows'
      with:
        name: luau-${{matrix.os.name}}
        path: |
          luau*
          *.a
    - uses: actions/upload-artifact@v2
      if: matrix.os.name == 'windows'
      with:
        name: luau-${{matrix.os.name}}
        path: |
          Release\luau*.exe
          Release\*.dll

